server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(?:iam-lab-|iam-)(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_name']
        regex: '/(?:iam-lab-|iam-)(?:keycloak|openldap|nginx).*'
        action: keep
    pipeline_stages:
      - match:
          selector: '{container=~".*keycloak.*"}'
          stages:
            - regex:
                expression: 'type=(?P<event_type>[A-Z_]+).*realmId=(?P<realm>[a-z-]+)'
            - labels:
                event_type:
                realm:
